# Generated by Django 4.0.6 on 2022-07-17 12:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,11}$')])),
                ('rg', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,13}$')])),
                ('celular', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{1,9}$')])),
                ('endereco', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{1,8}$')])),
                ('email', models.EmailField(max_length=254)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='digital_bank.contas')),
                ('data_transf', models.DateTimeField()),
                ('valor_transf', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo_transf', models.CharField(choices=[('-', 'Enviar'), ('+', 'Receber')], max_length=1)),
            ],
        ),
    ]
